### ISSUE TITLE
Any chance for an update

### ISSUE THREAD

**Issue by USFHunTer** [ningfei/Google-Translator-Tooltip-Expanded#17]
Hi, is there any chance that this script going to be updated?

**Comment by ningfei** [comment]
Hi, will have a look but I don't have the time currently. It works for me on Firefox/Chrome if I use the `google_value_tk` from previously working installation.  The problem is that `google_value_tk` is not correctly initialized. For a workaround, you can add an entry in the script's data in Violentmonkey: `google_value_tk`: `414415.99900568`. It should work then.

**Comment by USFHunTer** [comment]
I'd be thankful if you gave it a look when u got time.

**Comment by ningfei** [comment]
can try again now ca79b1e
